export const UPDATE_GLOBAL_STORE = 'UPDATE_GLOBAL_STORE';
export const NORMALIZE_PERSISTENT_STORE_DATA = 'NORMALIZE_PERSISTENT_STORE_DATA';

export const ADD_POSTS = 'ADD_POSTS';
export const EDIT_POST = 'EDIT_POST';
export const DELETE_POST = 'DELETE_POST';
export const UPVOTE_POST = 'UPVOTE_POST';
export const DOWNVOTE_POST = 'DOWNVOTE_POST';
export const UPDATE_ACTIVE_POST = 'UPDATE_ACTIVE_POST';

export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const UPDATE_ACTIVE_CATEGORY = 'UPDATE_ACTIVE_CATEGORY';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const UPVOTE_COMMENT = 'UPVOTE_COMMENT';
export const DOWNVOTE_COMMENT = 'DOWNVOTE_COMMENT';
export const UPDATE_ACTIVE_COMMENT = 'UPDATE_ACTIVE_COMMENT';

export const MODAL_ADD_POST_ENABLED = 'MODAL_ADD_POST_ENABLED';
export const MODAL_ADD_POST_DISABLED = 'MODAL_ADD_POST_DISABLED';
export const MODAL_EDIT_POST_ENABLED = 'MODAL_EDIT_POST_ENABLED';
export const MODAL_EDIT_POST_DISABLED = 'MODAL_EDIT_POST_DISABLED';
export const MODAL_ADD_COMMENT_ENABLED = 'MODAL_ADD_COMMENT_ENABLED';
export const MODAL_ADD_COMMENT_DISABLED = 'MODAL_ADD_COMMENT_DISABLED';
export const MODAL_EDIT_COMMENT_ENABLED = 'MODAL_EDIT_COMMENT_ENABLED';
export const MODAL_EDIT_COMMENT_DISABLED = 'MODAL_EDIT_COMMENT_DISABLED';

export const INCREMENT_COMMENTS_COUNT = 'INCREMENT_COMMENTS_COUNT';
export const DECREMENT_COMMENTS_COUNT = 'DECREMENT_COMMENTS_COUNT';

export const UPDATE_SORTING = 'UPDATE_SORTING';
